dist: trusty
env:
  global:
    - TF_VERSION=0.11.1

before_install:
  - |
    mkdir ~/bin
    export PATH=~/bin:$PATH
  - |
    echo "Fetching shellcheck"
    set -e
    wget -O ~/bin/shellcheck https://github.com/alphagov/paas-cf/releases/download/shellcheck_binary_0.4.6/shellcheck_linux_amd64
    chmod +x ~/bin/shellcheck
  - |
    echo "Fetching Terraform"
    set -e
    wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
    unzip -o terraform_${TF_VERSION}_linux_amd64.zip -d ~/bin
    rm terraform_${TF_VERSION}_linux_amd64.zip
  - pip install --user yamllint
  - eval "$(gimme 1.11)"
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega/...

script:
  - make test
