---
rule_files:
  # See alerts_validation_spec.rb for details of how this gets set:
  - spec/alerts/fixtures/rules.yml

evaluation_interval: 1h

tests:
  - interval: 1h
    input_series:
      - series: 'firehose_value_metric_cf_syslog_drain_scheduler_drains{bosh_job_id="1"}'
        values: 0 75 260

      - series: 'firehose_value_metric_cf_syslog_drain_scheduler_drains{bosh_job_id="2"}'
        values: 0 75 260

    alert_rule_test:

      # Alert should not be firing initially
      - eval_time: 1h
        alertname: CFSyslogDrains

      # Alert should be firing when there are more drains than the
      # number of adapters can handle: ceil(drains / 250)
      - eval_time: 2h
        alertname: CFSyslogDrains
        exp_alerts:
          - exp_labels:
              severity: warning
            exp_annotations:
              summary: "Syslog drain count is high"
              description: "Consider scaling the adapters to cope with the number of syslog drains. There are currently 2 adapter instances."
              required_adapters: 3
              url: "https://github.com/cloudfoundry/cf-syslog-drain-release/tree/v6.4#syslog-adapter"
