# Source: paas-auditor
---

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: AuditEventCollectionSlow
    rules:
      - alert: AuditEventCollectionSlow
        expr: (time() - informer_latest_cf_audit_event_timestamp) > 3600
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Audit event collection is too slow
          description: >
            The most recent event collected by the auditor is
            {{ $value | printf "%.0f" }} seconds in the past,
            but it should be less than 1 hour (3600 seconds) in the past.
            Check that the paas-auditor microservice is collecting events.
