# Source: firehose-exporter
---

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: CFSyslogDrains
    rules:
    - record: "firehose_value_metric_cf_syslog_drain_scheduler_drains:required_adapters"
      expr: ceil(sum(firehose_value_metric_cf_syslog_drain_scheduler_drains) / 250)

    - alert: CFSyslogDrains
      expr: "firehose_value_metric_cf_syslog_drain_scheduler_drains:required_adapters > ((adapter_instances))"
      labels:
        severity: warning
      annotations:
        summary: "Syslog drain count is high"
        description: "Consider scaling the adapters to cope with the number of syslog drains. There are currently ((adapter_instances)) adapter instances."
        required_adapters: "{{ humanize $value }}"
        url: "https://github.com/cloudfoundry/cf-syslog-drain-release/tree/v6.4#syslog-adapter"
