# Source: concourse
---

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: ConcourseSmoketestsFailures
    rules:
      - alert: ConcourseSmoketestsFailuresWarning
        expr: increase(concourse_builds_finished{exported_job="continuous-smoke-tests",pipeline="create-cloudfoundry",status="failed"}[1h]) >= 2
        labels:
          severity: warning
        annotations:
          summary: Concourse continuous-smoke-tests failures
          description: The continuous-smoke-tests Concourse job has failed at least twice in the last hour.

      - alert: ConcourseSmoketestsFailuresCritical
        expr: increase(concourse_builds_finished{exported_job="continuous-smoke-tests",pipeline="create-cloudfoundry",status="failed"}[30m]) >= 3
        labels:
          severity: critical
          notify: pagerduty-24-7
        annotations:
          summary: Concourse continuous-smoke-tests failures
          description: The continuous-smoke-tests Concourse job has failed at least three times in the last 30 minutes.

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: ConcourseSmoketestsRemoteFailures
    rules:
      - alert: ConcourseSmoketestsRemoteFailuresWarning
        expr: increase(concourse_builds_finished{exported_job="smoke-tests",pipeline=~"monitor-.+",status="failed"}[1h]) >= 2
        labels:
          severity: warning
        annotations:
          summary: "Concourse remote smoke-tests failures on {{ $labels.pipeline }} pipeline"
          description: "The Concourse job running smoke-tests remotely (in the {{ $labels.pipeline }} pipeline) has failed at least twice in the last hour."

      - alert: ConcourseSmoketestsRemoteFailuresCritical
        expr: increase(concourse_builds_finished{exported_job="smoke-tests",pipeline=~"monitor-.+",status="failed"}[30m]) >= 3
        labels:
          severity: critical
          notify: pagerduty-24-7
        annotations:
          summary: "Concourse remote smoke-tests failures on {{ $labels.pipeline }} pipeline"
          description: "The Concourse job running smoke-tests remotely (in the {{ $labels.pipeline }} pipeline) has failed at least three times in the last 30 minutes."
