# Source: paas-metrics
---

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: DopplerDroppedEnvelopes
    rules:
      - alert: DopplerDroppedEnvelopes
        expr: sum(increase(firehose_counter_event_loggregator_doppler_dropped_total[1h])) > 100
        labels:
          layer: logging
          severity: warning
        annotations:
          summary: "Doppler - dropped envelopes"
          description: "A Doppler VM dropped {{ $value | printf \"%.0f\" }} envelopes in an hour. Investigate whether this is a one-off or we need to scale our Dopplers."
