---

- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/login/oauth?/providers/microsoft
  value:
    type: oidc1.0
    authUrl: ((microsoft_oauth_auth_url))
    tokenUrl: ((microsoft_oauth_token_url))
    tokenKeyUrl: ((microsoft_oauth_token_key_url))
    issuer: ((microsoft_oauth_issuer))
    issuerValidationMode: domain_only
    redirectUrl: https://login.((system_domain))/uaa
    scopes:
      - openid
      - profile
      - email
    linkText: Microsoft
    showLinkText: true
    addShadowUserOnLogin: false
    relyingPartyId: ((microsoft_oauth_client_id))
    relyingPartySecret: ((microsoft_oauth_client_secret))
    skipSslValidation: false
    storeCustomAttributes: false
    attributeMappings:
      user_name: oid
