---

- type: replace
  path: /instance_groups/name=asapi/jobs/name=golangapiserver/properties/autoscaler/apiserver/broker/server/catalog/services/name=autoscaler
  value:
    id: 656a9276-a1f6-4646-aade-08f0a51b29ed
    name: autoscaler
    description: App instances autoscaler
    bindable: true
    tags:
      - autoscale
      - app
      - instance
      - schedule
      - rules
    metadata:
      displayName: Autoscaler
      longDescription: |
        Apps can be configured to dynamically increase or decrease the number of running instances using autoscaling.

        Scaling your app to fewer instances can reduce the cost during periods of low usage, eg at night.

        Scaling your app based on throughput or average latency can improve the user experience of your app during periods of high traffic, eg before a submission deadline.
      providerDisplayName: GOV.UK Platform as a Service
      documentationUrl: https://docs.cloud.service.gov.uk/managing_apps.html#autoscaling
      supportUrl: https://admin.london.cloud.service.gov.uk/support
      shareable: false
    plans:
    - id: 64d9552f-eede-439a-b49d-1efe17fccb1b
      name: default
      description: Configurable autoscaler to dynamically manage the number of instances for your application.
      free: false
      metadata:
        AdditionalMetadata:
          backups: false
          highlyAvailable: false
          version: standard
        displayName: Default
        bullets:
          - "Custom scaling rules"
          - "Custom scaling limits"
          - "Scheduled scaling"
