---

- type: replace
  path: /instance_groups/name=asactors/vm_type
  value: nano

- type: replace
  path: /instance_groups/name=asmetrics/vm_type
  value: nano

- type: replace
  path: /instance_groups/name=asapi/vm_type
  value: nano

- type: replace
  path: /instance_groups/name=asnozzle/vm_type
  value: nano
