---
rule_files:
  # See alerts_validation_spec.rb for details of how stdin gets set:
  - spec/alerts/fixtures/rules.yml

evaluation_interval: 1m

tests:
  - interval: 30m
    input_series:
      - series: 'node_filesystem_avail_bytes{instance="10.0.0.6:9100", mountpoint="/var/vcap/store"}'
        values: 2048 1024 512 256 128 64 32 16 8 4 2 1

    alert_rule_test:
      # Does not fire without enough data
      - eval_time: 0m
        alertname: BoshDirectorPersistentDiskFilling_Critical
      - eval_time: 55m
        alertname: BoshDirectorPersistentDiskFilling_Critical
      # Does not fire until consistently not scaling
      - eval_time: 90m
        alertname: BoshDirectorPersistentDiskFilling_Critical
        exp_alerts:
          - exp_labels:
              severity: critical
            exp_annotations:
              summary: "BOSH director's persistent disk will fill within the next 3 days"
              description: "In 3 days time the BOSH director's persistent disk will have 0 bytes available"
