buildpacks:
- name: binary_buildpack
  repo_name: binary-buildpack
  stack: cflinuxfs3
  version: v1.0.36
  sha: 8bf473f805b9e8deff6f58d57533737d6afe02fa3ad6a27073e73e100b2b0937
  filename: binary-buildpack-cflinuxfs3-v1.0.36.zip
  url: https://github.com/cloudfoundry/binary-buildpack/releases/download/v1.0.36/binary-buildpack-cflinuxfs3-v1.0.36.zip
  dependencies: []
- name: dotnet_core_buildpack
  repo_name: dotnet-core-buildpack
  stack: cflinuxfs3
  version: v2.3.6
  sha: cf358af4a3abcc3c96e6b09eaf1f5b8839840e2e5232269f5c0c16010f628465
  filename: dotnet-core-buildpack-cflinuxfs3-v2.3.6.zip
  url: https://github.com/cloudfoundry/dotnet-core-buildpack/releases/download/v2.3.6/dotnet-core-buildpack-cflinuxfs3-v2.3.6.zip
  dependencies:
  - name: bower
    version: 1.8.8
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.1.15
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.1.16
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 3.0.2
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 3.0.3
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 3.1.1
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 3.1.2
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.1.15
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.1.16
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 3.0.2
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 3.0.3
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 3.1.1
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 3.1.2
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.1.803
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.1.804
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 3.0.102
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 3.0.103
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 3.1.101
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 3.1.102
    cf_stacks:
    - cflinuxfs3
  - name: libgdiplus
    version: "6.0"
    cf_stacks:
    - cflinuxfs3
  - name: libunwind
    version: 1.3.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.19.0
    cf_stacks:
    - cflinuxfs3
- name: go_buildpack
  repo_name: go-buildpack
  stack: cflinuxfs3
  version: v1.9.7
  sha: d6714f5d3c0fb8e4156096f3b2435770f075e88fb88c0ebc8ceda78cbd53a2e9
  filename: go-buildpack-cflinuxfs3-v1.9.7.zip
  url: https://github.com/cloudfoundry/go-buildpack/releases/download/v1.9.7/go-buildpack-cflinuxfs3-v1.9.7.zip
  dependencies:
  - name: dep
    version: 0.5.4
    cf_stacks:
    - cflinuxfs3
  - name: glide
    version: 0.13.3
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.12.16
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.12.17
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.13.7
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.13.8
    cf_stacks:
    - cflinuxfs3
  - name: godep
    version: "80"
    cf_stacks:
    - cflinuxfs3
- name: java_buildpack
  repo_name: java-buildpack
  stack: cflinuxfs3
  version: v4.28
  sha: 3b0a9ba2af6217a8aa8b926223fe68e0ae5fe6e7e8d6527d9298f25a03299633
  filename: java-buildpack-v4.28.zip
  url: https://github.com/cloudfoundry/java-buildpack/releases/download/v4.28/java-buildpack-v4.28.zip
  dependencies: []
- name: nodejs_buildpack
  repo_name: nodejs-buildpack
  stack: cflinuxfs3
  version: v1.7.13
  sha: d31c98b6d81dc007f8ad875982276d7cdf91bb3bf01e7e417819766efd0ac14f
  filename: nodejs-buildpack-cflinuxfs3-v1.7.13.zip
  url: https://github.com/cloudfoundry/nodejs-buildpack/releases/download/v1.7.13/nodejs-buildpack-cflinuxfs3-v1.7.13.zip
  dependencies:
  - name: node
    version: 10.18.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.19.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 12.16.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 12.16.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 13.7.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 13.8.0
    cf_stacks:
    - cflinuxfs3
  - name: yarn
    version: 1.22.0
    cf_stacks:
    - cflinuxfs3
- name: php_buildpack
  repo_name: php-buildpack
  stack: cflinuxfs3
  version: v4.4.8
  sha: f404913f14175c3e19ed49ca088c1d0ae3ca0f392d9d47967b5ced6b66f6b553
  filename: php-buildpack-cflinuxfs3-v4.4.8.zip
  url: https://github.com/cloudfoundry/php-buildpack/releases/download/v4.4.8/php-buildpack-cflinuxfs3-v4.4.8.zip
  dependencies:
  - name: CAAPM
    version: 20.1.0
    cf_stacks:
    - cflinuxfs3
  - name: appdynamics
    version: 4.5.18.3343
    cf_stacks:
    - cflinuxfs3
  - name: composer
    version: 1.9.3
    cf_stacks:
    - cflinuxfs3
  - name: httpd
    version: 2.4.41
    cf_stacks:
    - cflinuxfs3
  - name: newrelic
    version: 9.1.0.246
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.16.1
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.17.8
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.2.27
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.2.28
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.3.13
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.3.15
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.4.2
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.4.3
    cf_stacks:
    - cflinuxfs3
- name: python_buildpack
  repo_name: python-buildpack
  stack: cflinuxfs3
  version: v1.7.8
  sha: 367dc94985eb4e89a10c9caedae28277b82db2f7bc4ee81a1b24ecbb3a093aaf
  filename: python-buildpack-cflinuxfs3-v1.7.8.zip
  url: https://github.com/cloudfoundry/python-buildpack/releases/download/v1.7.8/python-buildpack-cflinuxfs3-v1.7.8.zip
  dependencies:
  - name: libffi
    version: 3.2.1
    cf_stacks:
    - cflinuxfs3
  - name: libmemcache
    version: 1.0.18
    cf_stacks:
    - cflinuxfs3
  - name: miniconda3
    version: 4.7.12.1
    cf_stacks:
    - cflinuxfs3
  - name: pip-pop
    version: 0.1.4
    cf_stacks:
    - cflinuxfs3
  - name: pipenv
    version: 2018.11.26
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.5.7
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.5.9
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.6.9
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.6.10
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.7.5
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.7.6
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.8.0
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.8.1
    cf_stacks:
    - cflinuxfs3
  - name: setuptools
    version: 45.2.0
    cf_stacks:
    - cflinuxfs3
- name: ruby_buildpack
  repo_name: ruby-buildpack
  stack: cflinuxfs3
  version: v1.8.11
  sha: 85a16e49a2a0a8ec0a9f56f0275e0b25d2835afd4472dadb988b37a220b5a911
  filename: ruby-buildpack-cflinuxfs3-v1.8.11.zip
  url: https://github.com/cloudfoundry/ruby-buildpack/releases/download/v1.8.11/ruby-buildpack-cflinuxfs3-v1.8.11.zip
  dependencies:
  - name: bundler
    version: 1.17.3
    cf_stacks:
    - cflinuxfs3
  - name: bundler
    version: 2.1.4
    cf_stacks:
    - cflinuxfs3
  - name: jruby
    version: 9.1.17.0
    cf_stacks:
    - cflinuxfs3
  - name: jruby
    version: 9.2.10.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.19.0
    cf_stacks:
    - cflinuxfs3
  - name: openjdk1.8-latest
    version: 1.8.0
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.4.8
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.4.9
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.5.6
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.5.7
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.6.4
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.6.5
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.7.0
    cf_stacks:
    - cflinuxfs3
  - name: rubygems
    version: 3.1.2
    cf_stacks:
    - cflinuxfs3
  - name: yarn
    version: 1.22.0
    cf_stacks:
    - cflinuxfs3
- name: staticfile_buildpack
  repo_name: staticfile-buildpack
  stack: cflinuxfs3
  version: v1.5.4
  sha: 3dc69dcab29c37630abecccd4c1f47d6e5606bbcf7fc33710f843a5d6326c701
  filename: staticfile-buildpack-cflinuxfs3-v1.5.4.zip
  url: https://github.com/cloudfoundry/staticfile-buildpack/releases/download/v1.5.4/staticfile-buildpack-cflinuxfs3-v1.5.4.zip
  dependencies:
  - name: nginx
    version: 1.17.8
    cf_stacks:
    - cflinuxfs3
- name: nginx_buildpack
  repo_name: nginx-buildpack
  stack: cflinuxfs3
  version: v1.1.5
  sha: 06b44687d8906f3818a053d73293570ba165112ba9474188b22647047e7e7716
  filename: nginx-buildpack-cflinuxfs3-v1.1.5.zip
  url: https://github.com/cloudfoundry/nginx-buildpack/releases/download/v1.1.5/nginx-buildpack-cflinuxfs3-v1.1.5.zip
  dependencies:
  - name: nginx
    version: 1.16.1
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.17.8
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.13.6.2
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.15.8.2
    cf_stacks:
    - cflinuxfs3
- name: r_buildpack
  repo_name: r-buildpack
  stack: cflinuxfs3
  version: v1.1.1
  sha: 1470cdc2e06298637660079fe248a2fbe801c463620014263bde0f334191d279
  filename: r-buildpack-cflinuxfs3-v1.1.1.zip
  url: https://github.com/cloudfoundry/r-buildpack/releases/download/v1.1.1/r-buildpack-cflinuxfs3-v1.1.1.zip
  dependencies:
  - name: r
    version: 3.5.2
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.5.3
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.6.1
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.6.2
    cf_stacks:
    - cflinuxfs3
