buildpacks:
- name: binary_buildpack
  repo_name: binary-buildpack
  stack: cflinuxfs3
  version: v1.0.36
  sha: 8bf473f805b9e8deff6f58d57533737d6afe02fa3ad6a27073e73e100b2b0937
  filename: binary-buildpack-cflinuxfs3-v1.0.36.zip
  url: https://github.com/cloudfoundry/binary-buildpack/releases/download/v1.0.36/binary-buildpack-cflinuxfs3-v1.0.36.zip
  dependencies: []
- name: dotnet_core_buildpack
  repo_name: dotnet-core-buildpack
  stack: cflinuxfs3
  version: v2.3.3
  sha: 3b4e78bbfe8963e35851aa11539d7d65b9c84951f3a3b679f76ba3959653709e
  filename: dotnet-core-buildpack-cflinuxfs3-v2.3.3.zip
  url: https://github.com/cloudfoundry/dotnet-core-buildpack/releases/download/v2.3.3/dotnet-core-buildpack-cflinuxfs3-v2.3.3.zip
  dependencies:
  - name: bower
    version: 1.8.8
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.1.13
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.1.14
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 3.0.0
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 3.0.1
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 3.1.0
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.1.13
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.1.14
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 3.0.0
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 3.0.1
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 3.1.0
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.1.607
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.1.802
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 3.0.100
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 3.0.101
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 3.1.100
    cf_stacks:
    - cflinuxfs3
  - name: libgdiplus
    version: 6.0
    cf_stacks:
    - cflinuxfs3
  - name: libunwind
    version: 1.3.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.18.1
    cf_stacks:
    - cflinuxfs3
- name: go_buildpack
  repo_name: go-buildpack
  stack: cflinuxfs3
  version: v1.9.5
  sha: 095973fadbef43dd755f8029690b4764af5e56248972d7ef6f399c4caf32be78
  filename: go-buildpack-cflinuxfs3-v1.9.5.zip
  url: https://github.com/cloudfoundry/go-buildpack/releases/download/v1.9.5/go-buildpack-cflinuxfs3-v1.9.5.zip
  dependencies:
  - name: dep
    version: 0.5.4
    cf_stacks:
    - cflinuxfs3
  - name: glide
    version: 0.13.3
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.12.14
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.12.15
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.13.5
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.13.6
    cf_stacks:
    - cflinuxfs3
  - name: godep
    version: 80
    cf_stacks:
    - cflinuxfs3
- name: java_buildpack
  repo_name: java-buildpack
  stack: cflinuxfs3
  version: v4.27
  sha: 9e2c754732604b5c9e16c971d3fa975f184febb53316a08143696427186107de
  filename: java-buildpack-v4.27.zip
  url: https://github.com/cloudfoundry/java-buildpack/releases/download/v4.27/java-buildpack-v4.27.zip
  dependencies: []
- name: nodejs_buildpack
  repo_name: nodejs-buildpack
  stack: cflinuxfs3
  version: v1.7.9
  sha: 363aa8816d7172c537de60f4e9971d7f7b0684633f9648bd1420e64f860f1520
  filename: nodejs-buildpack-cflinuxfs3-v1.7.9.zip
  url: https://github.com/cloudfoundry/nodejs-buildpack/releases/download/v1.7.9/nodejs-buildpack-cflinuxfs3-v1.7.9.zip
  dependencies:
  - name: node
    version: 10.18.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.18.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 12.14.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 12.14.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 13.5.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 13.6.0
    cf_stacks:
    - cflinuxfs3
  - name: yarn
    version: 1.21.1
    cf_stacks:
    - cflinuxfs3
- name: php_buildpack
  repo_name: php-buildpack
  stack: cflinuxfs3
  version: v4.4.6
  sha: 43d208a3a3bc61fafcf65ba909281136bcbf4be765eccba514b5eed756e8c3d5
  filename: php-buildpack-cflinuxfs3-v4.4.6.zip
  url: https://github.com/cloudfoundry/php-buildpack/releases/download/v4.4.6/php-buildpack-cflinuxfs3-v4.4.6.zip
  dependencies:
  - name: CAAPM
    version: 10.7.0
    cf_stacks:
    - cflinuxfs3
  - name: appdynamics
    version: 4.5.17.3288
    cf_stacks:
    - cflinuxfs3
  - name: composer
    version: 1.9.1
    cf_stacks:
    - cflinuxfs3
  - name: httpd
    version: 2.4.41
    cf_stacks:
    - cflinuxfs3
  - name: newrelic
    version: 9.1.0.246
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.16.1
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.17.7
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.1.32
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.1.33
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.2.25
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.2.26
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.3.12
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.3.13
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.4.0
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.4.1
    cf_stacks:
    - cflinuxfs3
- name: python_buildpack
  repo_name: python-buildpack
  stack: cflinuxfs3
  version: v1.7.5
  sha: ef6f514b9c8f1a1c6500369b7bc29abd6bc89537a2c45385a31867ed294d6e48
  filename: python-buildpack-cflinuxfs3-v1.7.5.zip
  url: https://github.com/cloudfoundry/python-buildpack/releases/download/v1.7.5/python-buildpack-cflinuxfs3-v1.7.5.zip
  dependencies:
  - name: libffi
    version: 3.2.1
    cf_stacks:
    - cflinuxfs3
  - name: libmemcache
    version: 1.0.18
    cf_stacks:
    - cflinuxfs3
  - name: miniconda2
    version: 4.7.12.1
    cf_stacks:
    - cflinuxfs3
  - name: miniconda3
    version: 4.7.12.1
    cf_stacks:
    - cflinuxfs3
  - name: pip-pop
    version: 0.1.4
    cf_stacks:
    - cflinuxfs3
  - name: pipenv
    version: 2018.11.26
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 2.7.16
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 2.7.17
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.5.7
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.5.9
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.6.9
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.6.10
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.7.5
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.7.6
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.8.0
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.8.1
    cf_stacks:
    - cflinuxfs3
  - name: setuptools
    version: 42.0.2
    cf_stacks:
    - cflinuxfs3
- name: ruby_buildpack
  repo_name: ruby-buildpack
  stack: cflinuxfs3
  version: v1.8.8
  sha: f9ffffad0791e58b99236b472f29fd36969358f53661b029270cd785db5588c9
  filename: ruby-buildpack-cflinuxfs3-v1.8.8.zip
  url: https://github.com/cloudfoundry/ruby-buildpack/releases/download/v1.8.8/ruby-buildpack-cflinuxfs3-v1.8.8.zip
  dependencies:
  - name: bundler
    version: 1.17.3
    cf_stacks:
    - cflinuxfs3
  - name: bundler
    version: 2.1.4
    cf_stacks:
    - cflinuxfs3
  - name: jruby
    version: 9.1.17.0
    cf_stacks:
    - cflinuxfs3
  - name: jruby
    version: 9.2.9.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.18.1
    cf_stacks:
    - cflinuxfs3
  - name: openjdk1.8-latest
    version: 1.8.0
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.4.8
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.4.9
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.5.6
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.5.7
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.6.4
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.6.5
    cf_stacks:
    - cflinuxfs3
  - name: rubygems
    version: 3.1.2
    cf_stacks:
    - cflinuxfs3
  - name: yarn
    version: 1.21.1
    cf_stacks:
    - cflinuxfs3
- name: staticfile_buildpack
  repo_name: staticfile-buildpack
  stack: cflinuxfs3
  version: v1.5.3
  sha: 3afd87ea4d5ccc125d460584183b7108cbb9ada2e29688d7f5604da6af17dddd
  filename: staticfile-buildpack-cflinuxfs3-v1.5.3.zip
  url: https://github.com/cloudfoundry/staticfile-buildpack/releases/download/v1.5.3/staticfile-buildpack-cflinuxfs3-v1.5.3.zip
  dependencies:
  - name: nginx
    version: 1.17.7
    cf_stacks:
    - cflinuxfs3
- name: nginx_buildpack
  repo_name: nginx-buildpack
  stack: cflinuxfs3
  version: v1.1.4
  sha: 1d99e1857748d3f012e9b07548faa902478247c2b76a54143686bb0dfc501955
  filename: nginx-buildpack-cflinuxfs3-v1.1.4.zip
  url: https://github.com/cloudfoundry/nginx-buildpack/releases/download/v1.1.4/nginx-buildpack-cflinuxfs3-v1.1.4.zip
  dependencies:
  - name: nginx
    version: 1.16.1
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.17.7
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.13.6.2
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.15.8.2
    cf_stacks:
    - cflinuxfs3
- name: r_buildpack
  repo_name: r-buildpack
  stack: cflinuxfs3
  version: v1.1.1
  sha: 1470cdc2e06298637660079fe248a2fbe801c463620014263bde0f334191d279
  filename: r-buildpack-cflinuxfs3-v1.1.1.zip
  url: https://github.com/cloudfoundry/r-buildpack/releases/download/v1.1.1/r-buildpack-cflinuxfs3-v1.1.1.zip
  dependencies:
  - name: r
    version: 3.5.2
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.5.3
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.6.1
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.6.2
    cf_stacks:
    - cflinuxfs3
