buildpacks:
- name: binary_buildpack
  repo_name: binary-buildpack
  stack: cflinuxfs3
  version: v1.0.36
  sha: 8bf473f805b9e8deff6f58d57533737d6afe02fa3ad6a27073e73e100b2b0937
  filename: binary-buildpack-cflinuxfs3-v1.0.36.zip
  url: https://github.com/cloudfoundry/binary-buildpack/releases/download/v1.0.36/binary-buildpack-cflinuxfs3-v1.0.36.zip
  dependencies: []
- name: dotnet_core_buildpack
  repo_name: dotnet-core-buildpack
  stack: cflinuxfs3
  version: v2.3.9
  sha: f84d46df7c291a05ff2c2d16367533d49bbbc1ae7fb39b4da3e02a40fa688c38
  filename: dotnet-core-buildpack-cflinuxfs3-v2.3.9.zip
  url: https://github.com/cloudfoundry/dotnet-core-buildpack/releases/download/v2.3.9/dotnet-core-buildpack-cflinuxfs3-v2.3.9.zip
  dependencies:
  - name: bower
    version: 1.8.8
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.1.16
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.1.17
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 3.1.2
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 3.1.3
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.1.16
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.1.17
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 3.1.2
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 3.1.3
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.1.804
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.1.805
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 3.1.200
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 3.1.201
    cf_stacks:
    - cflinuxfs3
  - name: libgdiplus
    version: "6.0"
    cf_stacks:
    - cflinuxfs3
  - name: libunwind
    version: 1.4.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.20.1
    cf_stacks:
    - cflinuxfs3
- name: go_buildpack
  repo_name: go-buildpack
  stack: cflinuxfs3
  version: v1.9.12
  sha: 4e7120dd0474dee49861902e47cb1a55ecf2c9de917dcf4e913c650ac39292be
  filename: go-buildpack-cflinuxfs3-v1.9.12.zip
  url: https://github.com/cloudfoundry/go-buildpack/releases/download/v1.9.12/go-buildpack-cflinuxfs3-v1.9.12.zip
  dependencies:
  - name: dep
    version: 0.5.4
    cf_stacks:
    - cflinuxfs3
  - name: glide
    version: 0.13.3
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.13.9
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.13.10
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.14.1
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.14.2
    cf_stacks:
    - cflinuxfs3
  - name: godep
    version: "80"
    cf_stacks:
    - cflinuxfs3
- name: java_buildpack
  repo_name: java-buildpack
  stack: cflinuxfs3
  version: v4.30
  sha: 7b285fb4f85e6b443f360a7a02268cbcc5ee38f9e1602414bb604a1f63e3f461
  filename: java-buildpack-v4.30.zip
  url: https://github.com/cloudfoundry/java-buildpack/releases/download/v4.30/java-buildpack-v4.30.zip
  dependencies: []
- name: nodejs_buildpack
  repo_name: nodejs-buildpack
  stack: cflinuxfs3
  version: v1.7.18
  sha: 2c1b2abfd6e0072bda2e496a3d2f0db922638f027be5ba046da4ef1fdb3369e8
  filename: nodejs-buildpack-cflinuxfs3-v1.7.18.zip
  url: https://github.com/cloudfoundry/nodejs-buildpack/releases/download/v1.7.18/nodejs-buildpack-cflinuxfs3-v1.7.18.zip
  dependencies:
  - name: node
    version: 10.19.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.20.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 12.16.2
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 12.16.3
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 13.12.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 13.14.0
    cf_stacks:
    - cflinuxfs3
  - name: yarn
    version: 1.22.4
    cf_stacks:
    - cflinuxfs3
- name: php_buildpack
  repo_name: php-buildpack
  stack: cflinuxfs3
  version: v4.4.13
  sha: d038c50e0385e0efc819f6c92a53e87db99551af6b687eaa25d90535c9205791
  filename: php-buildpack-cflinuxfs3-v4.4.13.zip
  url: https://github.com/cloudfoundry/php-buildpack/releases/download/v4.4.13/php-buildpack-cflinuxfs3-v4.4.13.zip
  dependencies:
  - name: CAAPM
    version: 20.1.0
    cf_stacks:
    - cflinuxfs3
  - name: appdynamics
    version: 20.3.1.3604
    cf_stacks:
    - cflinuxfs3
  - name: composer
    version: 1.10.5
    cf_stacks:
    - cflinuxfs3
  - name: httpd
    version: 2.4.43
    cf_stacks:
    - cflinuxfs3
  - name: newrelic
    version: 9.1.0.246
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.16.1
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.17.10
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.2.29
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.2.30
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.3.16
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.3.17
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.4.4
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.4.5
    cf_stacks:
    - cflinuxfs3
- name: python_buildpack
  repo_name: python-buildpack
  stack: cflinuxfs3
  version: v1.7.13
  sha: 8cb8454b6d92d5216e2467917c8bd945cd77540a04ccc270f8c26e9ce3c76ede
  filename: python-buildpack-cflinuxfs3-v1.7.13.zip
  url: https://github.com/cloudfoundry/python-buildpack/releases/download/v1.7.13/python-buildpack-cflinuxfs3-v1.7.13.zip
  dependencies:
  - name: libffi
    version: 3.2.1
    cf_stacks:
    - cflinuxfs3
  - name: libmemcache
    version: 1.0.18
    cf_stacks:
    - cflinuxfs3
  - name: miniconda3
    version: 4.7.12.1
    cf_stacks:
    - cflinuxfs3
  - name: pip-pop
    version: 0.1.4
    cf_stacks:
    - cflinuxfs3
  - name: pipenv
    version: 2018.11.26
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.5.7
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.5.9
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.6.9
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.6.10
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.7.6
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.7.7
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.8.1
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.8.2
    cf_stacks:
    - cflinuxfs3
  - name: setuptools
    version: 46.1.3
    cf_stacks:
    - cflinuxfs3
- name: ruby_buildpack
  repo_name: ruby-buildpack
  stack: cflinuxfs3
  version: v1.8.17
  sha: 1a6a1828818621d62748d0c8faa498106e276c314ddb515c8d782ebec1f8ce54
  filename: ruby-buildpack-cflinuxfs3-v1.8.17.zip
  url: https://github.com/cloudfoundry/ruby-buildpack/releases/download/v1.8.17/ruby-buildpack-cflinuxfs3-v1.8.17.zip
  dependencies:
  - name: bundler
    version: 1.17.3
    cf_stacks:
    - cflinuxfs3
  - name: bundler
    version: 2.1.4
    cf_stacks:
    - cflinuxfs3
  - name: jruby
    version: 9.1.17.0
    cf_stacks:
    - cflinuxfs3
  - name: jruby
    version: 9.2.11.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.20.1
    cf_stacks:
    - cflinuxfs3
  - name: openjdk1.8-latest
    version: 1.8.0
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.5.7
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.5.8
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.6.5
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.6.6
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.7.0
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.7.1
    cf_stacks:
    - cflinuxfs3
  - name: rubygems
    version: 3.1.2
    cf_stacks:
    - cflinuxfs3
  - name: yarn
    version: 1.22.4
    cf_stacks:
    - cflinuxfs3
- name: staticfile_buildpack
  repo_name: staticfile-buildpack
  stack: cflinuxfs3
  version: v1.5.6
  sha: 79f92eb67c67f078ea032ab2f3b4989c265c640f70154738fef854964d1bd4ea
  filename: staticfile-buildpack-cflinuxfs3-v1.5.6.zip
  url: https://github.com/cloudfoundry/staticfile-buildpack/releases/download/v1.5.6/staticfile-buildpack-cflinuxfs3-v1.5.6.zip
  dependencies:
  - name: nginx
    version: 1.17.10
    cf_stacks:
    - cflinuxfs3
- name: nginx_buildpack
  repo_name: nginx-buildpack
  stack: cflinuxfs3
  version: v1.1.8
  sha: 708be5dc5fc1840d8848103152dadfaff91cdeebe7a7325e5c778d72251bdcaf
  filename: nginx-buildpack-cflinuxfs3-v1.1.8.zip
  url: https://github.com/cloudfoundry/nginx-buildpack/releases/download/v1.1.8/nginx-buildpack-cflinuxfs3-v1.1.8.zip
  dependencies:
  - name: nginx
    version: 1.16.1
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.17.10
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.13.6.2
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.15.8.3
    cf_stacks:
    - cflinuxfs3
- name: r_buildpack
  repo_name: r-buildpack
  stack: cflinuxfs3
  version: v1.1.4
  sha: b74eb8b6db3b58d94c2dc428b9cd8ec8e345a63f56e6eb13e20ccf62e2c39f07
  filename: r-buildpack-cflinuxfs3-v1.1.4.zip
  url: https://github.com/cloudfoundry/r-buildpack/releases/download/v1.1.4/r-buildpack-cflinuxfs3-v1.1.4.zip
  dependencies:
  - name: r
    version: 3.5.2
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.5.3
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.6.2
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.6.3
    cf_stacks:
    - cflinuxfs3
