---
- type: replace
  path: /addons/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases/domain=_.cell.service.cf.internal/targets
  value:
  - query: _
    instance_group: diego-cell
    network: cell
    deployment: ((deployment_name))
    domain: bosh
  - query: _
    instance_group: isolated-diego-cell
    network: cell
    deployment: ((deployment_name))
    domain: bosh

- type: replace
  path: /addons/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases/domain=gorouter.service.cf.internal/targets
  value:
  - query: '*'
    instance_group: router
    network: router
    deployment: ((deployment_name))
    domain: bosh

- type: replace
  path: /addons/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases/domain=autoscalerpostgres.service.cf.internal/targets
  value:
    - query: '*'
      instance_group: postgres_autoscaler
      deployment: app-autoscaler
      network: cf
      domain: bosh

- type: replace
  path: /addons/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases/domain=apiserver.service.cf.internal/targets
  value:
    - query: '*'
      instance_group: apiserver
      deployment: app-autoscaler
      network: cf
      domain: bosh

- type: replace
  path: /addons/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases/domain=autoscalerscheduler.service.cf.internal/targets
  value:
    - query: '*'
      instance_group: scheduler_autoscaler
      deployment: app-autoscaler
      network: cf
      domain: bosh

- type: replace
  path: /addons/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases/domain=servicebroker.service.cf.internal/targets
  value:
    - query: '*'
      instance_group: servicebroker
      deployment: app-autoscaler
      network: cf
      domain: bosh

- type: replace
  path: /addons/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases/domain=metricscollector.service.cf.internal/targets
  value:
    - query: '*'
      instance_group: metricscollector
      deployment: app-autoscaler
      network: cf
      domain: bosh

- type: replace
  path: /addons/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases/domain=eventgenerator.service.cf.internal/targets
  value:
    - query: '*'
      instance_group: eventgenerator
      deployment: app-autoscaler
      network: cf
      domain: bosh

- type: replace
  path: /addons/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases/domain=scalingengine.service.cf.internal/targets
  value:
    - query: '*'
      instance_group: scalingengine
      deployment: app-autoscaler
      network: cf
      domain: bosh

#remove consul jobs from all instance_groups
- type: remove
  path: /instance_groups/name=postgres_autoscaler/jobs/name=consul_agent
- type: remove
  path: /instance_groups/name=apiserver/jobs/name=consul_agent
- type: remove
  path: /instance_groups/name=scheduler_autoscaler/jobs/name=consul_agent
- type: remove
  path: /instance_groups/name=scalingengine/jobs/name=consul_agent
- type: remove
  path: /instance_groups/name=servicebroker/jobs/name=consul_agent
- type: remove
  path: /instance_groups/name=metricscollector/jobs/name=consul_agent
- type: remove
  path: /instance_groups/name=eventgenerator/jobs/name=consul_agent
- type: remove
  path: /instance_groups/name=operator/jobs/name=consul_agent

#disable consul of all jobs
- type: replace
  path: /instance_groups/name=apiserver/jobs/name=apiserver/properties/autoscaler/api_server/require_consul?
  value: false
- type: replace
  path: /instance_groups/name=scheduler_autoscaler/jobs/name=scheduler/properties/autoscaler/scheduler/require_consul?
  value: false
- type: replace
  path: /instance_groups/name=scalingengine/jobs/name=scalingengine/properties/autoscaler/require_consul?
  value: false
- type: replace
  path: /instance_groups/name=servicebroker/jobs/name=servicebroker/properties/autoscaler/service_broker/require_consul?
  value: false
- type: replace
  path: /instance_groups/name=metricscollector/jobs/name=metricscollector/properties/autoscaler/require_consul?
  value: false
- type: replace
  path: /instance_groups/name=eventgenerator/jobs/name=eventgenerator/properties/autoscaler/require_consul?
  value: false
- type: replace
  path: /instance_groups/name=operator/jobs/name=operator/properties/autoscaler/require_consul?
  value: false
