---
- type: replace
  path: /releases/-
  value:
    name: awslogs
    version: # 0.1.56
    url: # https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/rds-broker-0.1.56.tgz
    sha1: # 12395ade7d9671c0712f9132522656909954d73c
