---

- type: replace
  path: /releases/-
  value:
    name: consul
    version: 0.0.1604074535
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/consul-0.0.1604074535.tgz
    sha1: 906088c02337b5ed8922b9192c374260938bb57f

- type: replace
  path: /variables/-
  value:
    name: consul_ca
    type: certificate
    options:
      is_ca: true
      common_name: consulCA

- type: replace
  path: /variables/-
  value:
    name: consul_tls
    type: certificate
    options:
      ca: consul_ca
      common_name: consul
      extended_key_usage:
        - client_auth
        - server_auth
      alternative_names:
        - 127.0.0.1
        - localhost
        - "*.consul.service.cf.internal"
        - consul.service.cf.internal

- type: replace
  path: /variables/-
  value:
    name: vault_consul_tls
    type: certificate
    options:
      ca: consul_ca
      common_name: vault_consul
      extended_key_usage:
        - client_auth
        - server_auth
      alternative_names:
        - 127.0.0.1
        - localhost
        - "*.vault.service.cf.internal"
        - vault.service.cf.internal

- type: replace
  path: /addons/name=bosh-dns-aliases/jobs/name=bosh-dns-aliases/properties/aliases/-
  value:
    domain: consul.service.cf.internal
    targets:
    - query: '*'
      instance_group: consul
      deployment: ((deployment_name))
      network: ((network_name))
      domain: bosh

- type: replace
  path: /instance_groups/-
  value:
    name: consul
    instances: 1
    azs: [z1, z2, z3]
    networks: [{name: cf}]

    persistent_disk_type: 10GB

    stemcell: default
    vm_type: small
    update:
      canaries: 0
      max_in_flight: 50
      canary_watch_time: 1000-30000
      update_watch_time: 1000-30000
      serial: false

    jobs:
      - name: consul
        release: consul
        provides:
          consul_servers:
            as: consul_leaders
            shared: true
        consumes:
          consul_servers: { from: consul_leaders }
        properties:
          consul:
            ssl_ca: ((consul_ca.ca))
            ssl_cert: ((consul_tls.certificate))
            ssl_key: ((consul_tls.private_key))

      # - name: route_registrar
      #   release: routing
      #   properties:
      #     route_registrar:
      #       routes:
      #         - name: consul
      #           tls_port: 8500
      #           prepend_instance_index: false
      #           registration_interval: 10s
      #           uris:
      #             - consul.service.cf.internal
      #           server_cert_domain_san: consul.service.cf.internal

- type: replace
  path: /releases/-
  value:
    name: vault
    # FIXME
    version: 0.1.1
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/vault-0.1.1.tgz
    sha1: 1ec4d38c327110bf54e1eec25a3f10f162b1ed4c

- type: replace
  path: /variables/-
  value:
    name: vault_ca
    type: certificate
    options:
      is_ca: true
      common_name: vaultCA

- type: replace
  path: /variables/-
  value:
    name: vault_tls
    type: certificate
    options:
      ca: vault_ca
      common_name: vault
      extended_key_usage:
        - client_auth
        - server_auth
      alternative_names:
        - 127.0.0.1
        - localhost
        - "*.vault.service.cf.internal"
        - vault.service.cf.internal

- type: replace
  path: /variables/-
  value:
    name: vault_admin_password
    type: password
    options:
      length: 64

- type: replace
  path: /instance_groups/-
  value:
    name: vault
    instances: 1
    azs: [z1, z2, z3]
    networks: [{name: cf}]

    persistent_disk_type: 10GB

    stemcell: default
    vm_type: small
    vm_extensions:
      - vault_instance_profile

    jobs:
      - name: vault
        release: vault
        properties:
          tls:
            - name: vault
              key: ((vault_tls.private_key))
              cert: |
                ((vault_tls.certificate))
                ((vault_tls.ca))
            - name: "vault_consul_cert"
              cert: ((vault_consul_tls.certificate))
              key: ((vault_consul_tls.private_key))
            - name: "vault_consul_ca"
              cert: ((vault_consul_tls.ca))
          vault:
            config: |
              storage "consul" {
                address       = "consul.service.cf.internal:8500"
                path          = "vault"
                scheme        = "https"
                tls_ca_file   = "/var/vcap/jobs/vault/tls/vault_consul_ca/cert.pem"
                tls_cert_file = "/var/vcap/jobs/vault/tls/vault_consul_cert/cert.pem"
                tls_key_file  = "/var/vcap/jobs/vault/tls/vault_consul_cert/key.pem"
              }

              ui = true

              listener "tcp" {
                address = "0.0.0.0:8200"
                tls_cert_file = "/var/vcap/jobs/vault/tls/vault/cert.pem"
                tls_key_file  = "/var/vcap/jobs/vault/tls/vault/key.pem"
                tls_min_version = "tls12"
              }

              seal "awskms" {
                kms_key_id = "2c241c3d-80b6-4766-9eb3-62a66ce537b8"
              }

      - name: route_registrar
        release: routing
        properties:
          route_registrar:
            routes:
              - name: vault
                tls_port: 8200
                prepend_instance_index: false
                registration_interval: 10s
                uris:
                  - vault.((system_domain))
                  - vault.service.cf.internal
                server_cert_domain_san: vault.service.cf.internal

      - name: scripting
        release: generic-scripting
        properties:
          scripting:
            post-start-script: |
              set -ueo pipefail
              vault="/var/vcap/packages/vault/bin/vault"
              vault_ca_path_arg="-ca-path=/var/vcap/jobs/vault/tls/vault/cert.pem"

              for i in $(seq 60); do
                if [ $i -eq "60" ]; then
                  echo "vault not installed after $i attempts...giving up"
                  exit 1
                fi

                if [ -x $vault ]; then
                  break
                fi

                echo "waiting for vault to be installed"
                sleep 1
              done

              for i in $(seq 60); do
                if [ $i -eq "60" ]; then
                  echo "vault not up after $i attempts...giving up"
                  exit 1
                fi

                if $vault status $vault_ca_path_arg || [ $? = 2 ]; then
                  break
                fi

                echo "waiting for vault to be up"
                sleep 1
              done

              if grep -q 'Initialized\s*false' <<< $($vault status $vault_ca_path_arg); then
                echo "Vault not initialized, bootstrapping"
                init_output=$($vault operator init $vault_ca_path_arg -n 1 -t 1)

                if [ $? != 0]; then
                  echo "Attempted to init vault but did not succeed"
                  echo "$init_output"
                  exit 1
                fi

                token=$(echo "$init_output" | grep -o 'Token: .*' | awk '{print $2}')

                $vault login $vault_ca_path_arg $token
                if [ $? != 0 ]; then
                  echo "Attempted to log in to vault but did not succeed"
                  exit 1
                fi

                $vault auth enable $vault_ca_path_arg userpass
                if [ $? != 0 ]; then
                  echo "Attempted to enable userpass but did not succeed"
                  exit 1
                fi

                $vault policy write $vault_ca_path_arg admin <(cat <<POLICY
              # yes this indentation is correct
              path "auth/*" {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }

              path "sys/auth/*" {
                capabilities = ["create", "update", "delete", "sudo"]
              }

              path "sys/auth" {
                capabilities = ["read"]
              }

              path "sys/policies/acl/*" {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }

              path "sys/policies/acl" {
                capabilities = ["list"]
              }

              path "secret/*" {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }

              path "sys/mounts/*" {
                capabilities = ["create", "read", "update", "delete", "list", "sudo"]
              }

              path "sys/health" {
                capabilities = ["read", "sudo"]
              }

              path "sys/capabilities" {
                capabilities = ["create", "update"]
              }

              path "sys/capabilities-self" {
                capabilities = ["create", "update"]
              }
              POLICY
                )

                $vault write $vault_ca_path_arg auth/userpass/users/admin "password=((vault_admin_password))" policies=admin
                if [ $? != 0 ]; then
                  echo "Attempted to add admin user but did not succeed"
                  exit 1
                fi

              else
                echo "Vault already initialized"
              fi

              if grep -q 'Sealed\s*true' <<< $($vault status $vault_ca_path_arg); then
                echo "Vault should be unsealed but is sealed...giving up"
                exit 1
              fi

- type: replace
  path: /releases/-
  value:
    name: "generic-scripting"
    version: "3"
    url: "https://bosh.io/d/github.com/orange-cloudfoundry/generic-scripting-release?v=3"
    sha1: "3198161324c49c670282f5c64b471204a3c510bb"
