# ---

# - type: replace
#   path: /releases/-
#   value:
#     name: consul
#     version: 0.0.1603348629
#     url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/consul-0.0.1603348629.tgz
#     sha1: ac2492c0ca5eefa30b1c184d3954bef9cd679d72

# - type: replace
#   path: /variables/-
#   value:
#     name: consul_ca
#     type: certificate
#     options:
#       is_ca: true
#       common_name: consulCA

# - type: replace
#   path: /variables/-
#   value:
#     name: consul_tls
#     type: certificate
#     options:
#       ca: consul_ca
#       common_name: consul
#       extended_key_usage:
#         - client_auth
#         - server_auth
#       alternative_names:
#         - 127.0.0.1
#         - localhost
#         - "*.consul.service.cf.internal"
#         - consul.service.cf.internal

# - type: replace
#   path: /instance_groups/-
#   value:
#     name: consul
#     instances: 3
#     azs: [z1, z2, z3]
#     networks: [{name: cf}]

#     persistent_disk_type: 10GB

#     stemcell: default
#     vm_type: small
#     update:
#       canaries: 0
#       max_in_flight: 50
#       canary_watch_time: 1000-30000
#       update_watch_time: 1000-30000
#       serial: false

#     jobs:
#       - name: consul
#         release: consul
#         provides:
#           consul_servers:
#             as: consul_leaders
#             shared: true
#         consumes:
#           consul_servers: { from: consul_leaders }
#         properties:
#           consul:
#             ssl_ca: ((consul_ca.ca))
#             ssl_cert: ((consul_tls.certificate))
#             ssl_key: ((consul_tls.private_key))

#       - name: route_registrar
#         release: routing
#         properties:
#           route_registrar:
#             routes:
#               - name: consul
#                 tls_port: 8500
#                 prepend_instance_index: false
#                 registration_interval: 10s
#                 uris:
#                   - consul.service.cf.internal
#                 server_cert_domain_san: consul.service.cf.internal
