---

- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggregator_agent/properties/deployment?
  value: ((environment))
- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggregator_agent/properties/tags?/deployment
  value: ((environment))
- type: replace
  path: /addons/name=forwarder_agent/jobs/name=loggr-forwarder-agent/properties/deployment?
  value: ((environment))
- type: replace
  path: /addons/name=forwarder_agent/jobs/name=loggr-forwarder-agent/properties/tags?/deployment
  value: ((environment))

- type: replace
  path: /releases/name=loggregator
  value:
    name: "loggregator"
    version: "106.3.6"
    url: "https://bosh.io/d/github.com/cloudfoundry/loggregator-release?v=106.3.6"
    sha1: "ba64ea33a88429a1031f4041dcb7665519da4aa2"
