---

- type: remove
  path: /instance_groups/name=router/vm_extensions

- type: remove
  path: /instance_groups/name=router/jobs/name=gorouter/properties/routing_api

- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/router/drain_wait?
  value: 120

- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/router/tls_port?
  value: 8443

- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/router/status/user
  value: router_user

- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/router/http_rewrite?
  value:
    responses:
      add_headers_if_not_present:
        - name: Strict-Transport-Security
          value: max-age=31536000; includeSubDomains; preload

- type: replace
  path: /instance_groups/name=router/networks/0/name
  value: router

- type: replace
  path: /instance_groups/name=router/vm_extensions?/-
  value: cf_router_target_groups
