---
- type: replace
  path: /releases/-
  value:
    name: traefik
    sha1: 0befd0d0c63b6ba457e00867bdfd5a9af57e7c01
    url: https://s3.eu-west-3.amazonaws.com/traefik-boshrelease/compiled-releases/traefik/traefik-1.6.0-ubuntu-xenial-250.48-20190520-233224-508752875-20190520233225.tgz
    version: 1.6.0

- type: replace
  path: /instance_groups/-
  value:
    name: traefik
    azs: [z1, z2, z3]
    instances: 3
    jobs:
      - name: traefik
        release: traefik
        properties:
          traefik:
            log_level: INFO
            access_logs: { enabled: true }
            http: { enabled: true }
            tls:
              cert: ((traefik_tls))
          bpm:
            enabled: true
      - name: bpm
        release: bpm
      - name: smoke-tests
        release: traefik
    stemcell: default
    persistent_disk_type: default
    env:
      bosh: { swap_size: 0 }
    networks:
      - name: ((network_name))

- type: replace
  path: /variables/name=traefikCA?
  value:
    type: certificate
    options:
      is_ca: true
      common_name: traefikCA

- type: replace
  path: /variables/name=traefik_tls?
  value:
    type: certificate
    options:
      ca: ((traefikCA))
      common_name: traefik
      alternative_names:
        - traefik
        - "*.traefik"

- type: replace
  path: /features?/use_dns_addresses
  value: true
