---
- type: replace
  path: /releases/-
  value:
    name: traefik
    version: 0.0.1562076258
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/traefik-0.0.1562076258.tgz
    sha1: 421dea4877a009bc028188d3313ed7aef1ec2df5

- type: replace
  path: /instance_groups/name=router/jobs/-
  value:
    name: traefik
    release: traefik
    properties:
      bpm:
        enabled: true
      traefik:
        log_level: DEBUG
        access_logs: { enabled: true }
        http:
          enabled: true
          port: 83
          redirect_to_https: true
        tls:
          cert:
            certificate: "((router_ssl.certificate))"
            private_key: "((router_ssl.private_key))"
          enabled: true
        additionalEntryPoints: |
          [entryPoints.healthcheck]
            address = ":82"
        file:
          enabled: true
          rules: |
            [file]
            [frontends]
              [frontends.defaultFrontend]
              backend = "gorouter"
              passHostHeader = true
              entrypoints = ["https"]
              priority = 1

              [frontends.defaultFrontend.routes]
                [frontends.defaultFrontend.routes.catchAll]
                rule = "HostRegexp:{catchall:.*}"

              [frontends.defaultFrontend.headers]
              STSPreload = true
              STSIncludeSubdomains = true
              forceSTSHeader = true

              [frontends.healthcheck]
              backend = "gorouterHealthcheck"
              entrypoints = ["healthcheck"]

            [backends]
              [backends.gorouter]
                [backends.gorouter.healthcheck]
                path = "/health"
                port = 8080
                interval = "5s"
                scheme = "http"

                [backends.gorouter.servers.server1]
                url = "http://127.0.0.1:80"

              [backends.gorouterHealthcheck]
                [backends.gorouterHealthcheck.servers.server1]
                url = "http://127.0.0.1:8080"
  # - name: smoke-tests
  #   release: traefik

  # missing external healthcheck for go routers

- type: replace
  path: /variables/-
  value:
    name: traefikCA
    type: certificate
    options:
      is_ca: true
      common_name: traefikCA

- type: replace
  path: /features?/use_dns_addresses
  value: true

- type: replace
  path: /instance_groups/name=router/vm_extensions?/-
  value: cf_router_system_domain_target_groups

- type: replace
  path: /instance_groups/name=router/vm_extensions?/-
  value: cf_router_system_domain_sg
