---
- type: replace
  path: /releases/-
  value:
    name: traefik
    sha1: e5d3b97a64b09c32ac759ce777f1ee001bbd7816
    url: https://github.com/gstackio/traefik-boshrelease/releases/download/v1.6.0/traefik-1.6.0.tgz
    version: 1.6.0

- type: replace
  path: /instance_groups/-
  value:
    name: traefik
    azs: [z1, z2, z3]
    instances: ((traefik_instances))
    vm_type: medium
    jobs:
      - name: traefik
        release: traefik
        properties:
          traefik:
            log_level: INFO
            access_logs: { enabled: true }
            http: { enabled: true }
            tls:
              cert: ((traefik_tls))
          bpm:
            enabled: true
      # - name: smoke-tests
      #   release: traefik
    stemcell: default
    persistent_disk_type: 10GB
    env:
      bosh: { swap_size: 0 }
    networks:
      - name: ((network_name))

- type: replace
  path: /variables/-
  value:
    name: traefikCA
    type: certificate
    options:
      is_ca: true
      common_name: traefikCA

- type: replace
  path: /variables/-
  value:
    name: traefik_tls
    type: certificate
    options:
      ca: traefikCA
      common_name: traefik
      alternative_names:
        - traefik
        - "*.traefik"

- type: replace
  path: /features?/use_dns_addresses
  value: true
