---
- type: replace
  path: /releases/name=capi
  value:
    name: "capi"
    version: "1.97.0"
    url: "https://bosh.io/d/github.com/cloudfoundry/capi-release?v=1.97.0"
    sha1: "876530fb5546f9d166ecaca55e5475f0ec5888d3"
