---
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/encryption
  value:
    active_key_label: ((uaa_default_encryption_passphrase_id))
    encryption_keys:
    - label: ((uaa_default_encryption_passphrase_id))
      passphrase: ((uaa_default_encryption_passphrase))
    - label: ((uaa_default_encryption_passphrase_id_old))
      passphrase: ((uaa_default_encryption_passphrase_old))

- type: replace
  path: /variables/-
  value:
    name: uaa_default_encryption_passphrase_old
    type: password

- type: replace
  path: /variables/-
  value:
    name: uaa_default_encryption_passphrase_id
    type: password

- type: replace
  path: /variables/-
  value:
    name: uaa_default_encryption_passphrase_id_old
    type: password
