---
- type: replace
  path: /releases/name=uaa
  value:
    name: "uaa"
    version: "73.4.0"
    url: "https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=73.4.0"
    sha1: "02a68b974150394d733015fba0a2be0ab2cd84c4"
