---
- type: replace
  path: /releases/name=uaa
  value:
    name: uaa
    version: 0.1.21
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/uaa-0.1.21.tgz
    sha1: 35fe120746fd0c58308963c31b903543b314ce3c
