---
- type: replace
  path: /releases/name=uaa
  value:
    name: uaa
    version: 0.1.22
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/uaa-0.1.22.tgz
    sha1: d9185ca9658db699b6025b3542d3c747e15e6dd9
