---

- type: replace
  path: /instance_groups/name=log-api/vm_extensions?/-
  value: cf_doppler_elbs

- type: replace
  path: /instance_groups/name=log-api/vm_extensions?/-
  value: cf_loggregator_rlp_target_groups

- type: remove
  path: /instance_groups/name=log-api/jobs/name=route_registrar

- type: replace
  path: /instance_groups/name=log-api/jobs/name=loggregator_trafficcontroller/properties/system_domain
  value: ((terraform_outputs_cf_root_domain))

- type: replace
  path: /instance_groups/name=log-api/azs/-
  value: z3

- type: replace
  path: /instance_groups/name=log-api/instances
  value: ((log_api_instances))

- type: replace
  path: /releases/name=loggregator
  # We cannot use a version of loggregator past 105.5 until we get rid of ELBs
  # This is because of TLS cipher suite mismatch
  value:
    name: "loggregator"
    version: "105.5"
    url: "https://bosh.io/d/github.com/cloudfoundry/loggregator-release?v=105.5"
    sha1: "62b9210def7c5179f6088b9449f551f57f1a1ee8"

