---
- type: replace
  path: /releases/-
  value:
    name: "prometheus"
    version: "26.2.0"
    url: "https://bosh.io/d/github.com/cloudfoundry-community/prometheus-boshrelease?v=26.2.0"
    sha1: "9a57a9c74ebcb53baaa9cf8eb22f8ef353460169"

- type: replace
  path: /addons?/-
  value:
    name: prometheus-blackbox-exporter
    jobs:
      - name: blackbox_exporter
        release: prometheus
        properties:
          blackbox_exporter:
            config:
              modules:
                dns_canary:
                  prober: dns
                  timeout: 1s
                  dns:
                    query_name: __canary.((system_domain))
                    query_type: "A"
