---
- type: replace
  path: /releases/-
  value:
    name: rds-broker
    version: 0.1.60
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/rds-broker-0.1.60.tgz
    sha1: c08661a2e3e7cec721a6929e2676aa288779d11e

- type: replace
  path: /instance_groups/-
  value:
    name: rds_broker
    azs: [z1, z2]
    instances: 2
    vm_type: medium
    vm_extensions:
      - rds_broker
    stemcell: default
    networks:
      - name: cf

- type: replace
  path: /instance_groups/name=rds_broker/jobs?/-
  value:
    name: rds-metric-collector
    release: rds-broker
    properties:
      rds-metric-collector:
        aws:
          aws_region: "((terraform_outputs_region))"
        rds-broker:
          broker_name: "((terraform_outputs_environment))"
          db_prefix: "rdsbroker"
          master_password_seed: ((secrets_rds_broker_master_password_seed))
        loggregator:
          ca_cert: "((loggregator_rds_metrics_collector.ca))"
          client_cert: "((loggregator_rds_metrics_collector.certificate))"
          client_key: "((loggregator_rds_metrics_collector.private_key))"
        locket:
          api_location: "locket.service.cf.internal:8891"
          ca_cert: "((diego_locket_client.ca))"
          client_cert: "((diego_locket_client.certificate))"
          client_key: "((diego_locket_client.private_key))"
        scheduler:
          sql_metrics_collector_interval: 60
          cloudwatch_metrics_collector_interval: 300

- type: replace
  path: /instance_groups/name=rds_broker/jobs?/-
  value:
    name: rds-broker
    release: rds-broker
    properties:
      rds-broker:
        allow_user_provision_parameters: true
        allow_user_update_parameters: true
        aws_region: "((terraform_outputs_region))"
        password: ((secrets_rds_broker_admin_password))
        state_encryption_key: ((secrets_rds_broker_state_encryption_key))
        db_prefix: "rdsbroker"
        master_password_seed: ((secrets_rds_broker_master_password_seed))
        broker_name: "((terraform_outputs_environment))"
        cron_schedule: "@daily"
        keep_snapshots_for_days: 35

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/security_group_definitions/-
  value:
    name: rds_broker_instances
    rules:
      - protocol: tcp
        destination: ((terraform_outputs_aws_backing_service_cidr_all))
        ports: '5432'
      - protocol: tcp
        destination: ((terraform_outputs_aws_backing_service_cidr_all))
        ports: '3306'

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/default_running_security_groups/-
  value: rds_broker_instances

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/default_staging_security_groups/-
  value: rds_broker_instances

- type: replace
  path: /variables/-
  value:
    name: secrets_rds_broker_admin_password
    type: password
- type: replace
  path: /variables/-
  value:
    name: secrets_rds_broker_master_password_seed
    type: password
- type: replace
  path: /variables/-
  value:
    name: secrets_rds_broker_state_encryption_key
    type: password
- type: replace
  path: /variables/-
  value:
    name: loggregator_rds_metrics_collector
    type: certificate
    options:
      ca: loggregator_ca
      common_name: loggregator_rds_metrics_collector
      extended_key_usage:
        - client_auth
        - server_auth

- type: replace
  path: /meta?/rds_broker
  value:
    default_mssql_rds_properties: &default_mssql_rds_properties
      storage_type: "gp2"
      auto_minor_version_upgrade: true
      multi_az: false
      storage_encrypted: false
      publicly_accessible: false
      copy_tags_to_snapshot: true
      skip_final_snapshot: false
      backup_retention_period: 7
      db_subnet_group_name: ((terraform_outputs_rds_broker_dbs_subnet_group))
      vpc_security_group_ids:
        - ((terraform_outputs_rds_broker_dbs_security_group_id))
      engine: sqlserver-se
      engine_version: "14.00.3223.3.v1"
      engine_family: sqlserver-se-14.0
      license_model: license-included

    large_plan_rds_properties: &large_plan_rds_properties
      db_instance_class: "db.m4.large"
      allocated_storage: 20
      backup_retention_period: 0
      skip_final_snapshot: true

- type: replace
  path: /instance_groups/name=rds_broker/jobs/name=rds-broker/properties/rds-broker/catalog?/services?/-
  value:
    id: f4deaddf-3936-4e18-8716-4fdd6a9faec0
    name: mssql
    description: "AWS RDS MSSQL service"
    bindable: true
    tags:
      - mssql
      - relational
    metadata:
      displayName: "AWS RDS MSSQL"
      imageUrl: ""
      longDescription: "AWS RDS mssql service"
      providerDisplayName: "Amazon Web Services"
      documentationUrl: "https://aws.amazon.com/documentation/rds/"
      supportUrl: "¯\_(ツ)_/¯"
    plan_updateable: true

- type: replace
  path: /instance_groups/name=rds_broker/jobs/name=rds-broker/properties/rds-broker/catalog/services/name=mssql/plans?/-
  value:
    id: 47eb5baa-3818-4edc-98bd-e1c4f5941f5a
    name: large-14
    description: "20GB Storage, NOT BACKED UP, Dedicated Instance. MSSQL Version 14 2017. DB Instance Class: db.m4.large."
    free: true
    metadata:
      bullets:
        - "Dedicated MSSQL 2017 server"
        - "AWS RDS"
    rds_properties:
      <<: *default_mssql_rds_properties # yamllint disable-line
      <<: *large_plan_rds_properties # yamllint disable-line
