---
- type: replace
  path: /meta?/elasticache_broker
  value:
    cache_cluster_config: &elasticache_cache_cluster_config
      shard_count: 1
      snapshot_retention_limit: 7
      parameters:
        cluster-enabled: 'no'
        maxmemory-policy: volatile-lru
        reserved-memory: '0'

    non_ha_plan: &elasticache_non_ha_plan
      replicas_per_node_group: 0
      automatic_failover_enabled: false

    ha_plan: &elasticache_ha_plan
      replicas_per_node_group: 1
      automatic_failover_enabled: true

    tiny_plan: &elasticache_tiny_plan
      instance_type: cache.t2.small

    small_plan: &elasticache_small_plan
      instance_type: cache.t2.medium

    medium_plan: &elasticache_medium_plan
      instance_type: cache.m5.large

- type: replace
  path: /releases/-
  value:
    name: elasticache-broker
    version: 0.1.8
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/elasticache-broker-0.1.8.tgz
    sha1: a1b83e8f8972b71756bc622442590f34ff72a551

- type: replace
  path: /addons/name=loggregator_agent/exclude/jobs/-
  value:
    name: elasticache-broker
    release: elasticache-broker

- type: replace
  path: /instance_groups/-
  value:
    name: elasticache_broker
    azs: [z1, z2]
    instances: 2
    vm_type: nano
    vm_extensions:
      - elasticache_broker
    stemcell: default
    networks:
      - name: cf
    jobs:
      - name: elasticache-broker
        release: elasticache-broker
        properties:
          elasticache-broker:
            broker_name: "elasticache-broker"
            broker_username: "elasticache-broker"
            broker_password: ((secrets_elasticache_broker_admin_password))
            kms_key_id: alias/elasticache-broker
            secrets_manager_path: elasticache-broker/((environment))
            region: "((terraform_outputs_region))"
            cache_subnet_group_name: ((terraform_outputs_elasticache_broker_subnet_group_name))
            vpc_security_group_ids:
            - ((terraform_outputs_elasticache_broker_instances_security_group_id))

            catalog:
              services:
                - id: 7b94ab02-478f-4c1b-95d8-21522672930b
                  name: redis
                  description: AWS ElastiCache Redis service
                  metadata:
                    displayName: Redis
                    imageUrl: https://redis.io/images/redis-white.png
                    longDescription: AWS ElastiCache Redis cluster
                    providerDisplayName: GOV.UK PaaS
                    documentationUrl: https://docs.cloud.service.gov.uk/#redis
                    supportUrl: https://www.cloud.service.gov.uk/support.html
                  tags:
                    - elasticache
                    - redis
                  bindable: true
                  plan_updateable: true
                  plans:
                    - id: 3a51701c-eef3-447c-882b-907ad2bcb7ab
                      name: tiny-clustered-3.2
                      description: DEPRECATED - do not use, 568MB RAM, clustered (1 shard), single node, no failover, daily backups
                      free: true
                      metadata:
                        displayName: Redis 3.2 Clustered Tiny
                    - id: c84d1bef-9500-4ce9-88b2-c0bd421bbf8a
                      name: tiny-3.2
                      description: 568MB RAM, single node, no failover, daily backups (for instances created after 21/1/2019)
                      free: true
                      metadata:
                        displayName: Redis 3.2 tiny
                    - id: b6949ea7-5c98-4c69-b981-4b5318ea8b7c
                      name: medium-ha-3.2
                      description: 6.37GB RAM, highly-available, daily backups
                      free: false
                      metadata:
                        displayName: Redis 3.2 medium highly-available
                    - id: ea5c8cc3-74e6-4b15-bd61-bbe244cfe63d
                      name: tiny-ha-3.2
                      description: 1.5GB RAM, highly-available, daily backups
                      free: false
                      metadata:
                        displayName: Redis tiny highly-available
                    - id: 9162ed5b-0c88-4f43-bcaf-c6d4a45dd243
                      name: small-ha-3.2
                      description: 3GB RAM, highly-available, daily backups
                      free: false
                      metadata:
                        displayName: Redis 3.2 small highly-available

            plan_configs:
              3a51701c-eef3-447c-882b-907ad2bcb7ab:
                <<: *elasticache_cache_cluster_config # yamllint disable-line
                <<: *elasticache_non_ha_plan # yamllint disable-line
                instance_type: cache.t2.micro
                parameters:
                  cluster-enabled: 'yes'

              c84d1bef-9500-4ce9-88b2-c0bd421bbf8a:
                <<: *elasticache_cache_cluster_config # yamllint disable-line
                <<: *elasticache_non_ha_plan # yamllint disable-line
                instance_type: cache.t2.micro
                automatic_failover_enabled: false

              b6949ea7-5c98-4c69-b981-4b5318ea8b7c:
                <<: *elasticache_cache_cluster_config # yamllint disable-line
                <<: *elasticache_ha_plan # yamllint disable-line
                <<: *elasticache_medium_plan # yamllint disable-line

              ea5c8cc3-74e6-4b15-bd61-bbe244cfe63d:
                <<: *elasticache_cache_cluster_config # yamllint disable-line
                <<: *elasticache_ha_plan # yamllint disable-line
                <<: *elasticache_tiny_plan # yamllint disable-line

              9162ed5b-0c88-4f43-bcaf-c6d4a45dd243:
                <<: *elasticache_cache_cluster_config # yamllint disable-line
                <<: *elasticache_ha_plan # yamllint disable-line
                <<: *elasticache_small_plan # yamllint disable-line


- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/security_group_definitions/-
  value:
    name: elasticache_broker_instances
    rules:
      - protocol: tcp
        destination: ((terraform_outputs_aws_backing_service_cidr_all))
        ports: '6379'

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/default_running_security_groups/-
  value: elasticache_broker_instances

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/default_staging_security_groups/-
  value: elasticache_broker_instances

- type: replace
  path: /variables/-
  value:
    name: secrets_elasticache_broker_admin_password
    type: password
