---
- type: replace
  path: /releases/-
  value:
    name: "prometheus"
    version: "26.3.0"
    url: "https://bosh.io/d/github.com/cloudfoundry-community/prometheus-boshrelease?v=26.3.0"
    sha1: "d945d88b23dbfea03959d5404450567a90a7d833"

- type: replace
  path: /addons?/-
  value:
    name: prometheus-blackbox-exporter
    exclude:
      deployments:
        - concourse  # from paas-bootstrap
        - prometheus # has a separate version
    jobs:
      - name: blackbox_exporter
        release: prometheus
        properties:
          blackbox_exporter:
            config:
              modules:
                dns_canary:
                  prober: dns
                  timeout: 1s
                  dns:
                    query_name: __canary.((system_domain))
                    query_type: "A"
