---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: e1ffec0d1940706f157a8c1e0ab8131b7084fa1c
inputs:
  - name: paas-cf
  - name: cf-manifest
  - name: admin-creds
run:
  path: sh
  args:
    - -e
    - -u
    - -c
    - |
      if [ "${DISABLE_ADMIN_USER_CREATION:-}" = "true" ]; then
        echo "Temporary user creation is disabled (DISABLE_ADMIN_USER_CREATION=${DISABLE_ADMIN_USER_CREATION}). Skipping."
        exit 0
      fi

      USERNAME=$(cat admin-creds/username)

      echo "Removing user ${USERNAME}"

      cf api "${API_ENDPOINT}"
      cf auth "${CF_ADMIN}" "${CF_PASS}"

      cf delete-user "${USERNAME}" -f
