---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: 864e80c4793e4fca17a2374e8075af119dd03162
inputs:
  - name: paas-cf
  - name: cf-manifest
  - name: admin-creds
run:
  path: sh
  args:
    - -e
    - -u
    - -c
    - |
      if [ "${DISABLE_ADMIN_USER_CREATION:-}" = "true" ]; then
        echo "Temporary user creation is disabled (DISABLE_ADMIN_USER_CREATION=${DISABLE_ADMIN_USER_CREATION}). Skipping."
        exit 0
      fi

      USERNAME=$(cat admin-creds/username)

      echo "Removing user ${USERNAME}"

      echo | cf login -a "${API_ENDPOINT}" -u "${CF_ADMIN}" -p "${CF_PASS}"

      cf delete-user "${USERNAME}" -f
