platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/bosh-cli-v2
    tag: f91084a42c34535e5b9ad61226314155b0854648

run:
  path: sh
  args:
    - -e
    - -c
    - |
      credhub login
      credhub generate --name "$DESTINATION" --type ssh
      credhub get --name "$DESTINATION" --key public_key
