platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/bosh-cli-v2
    tag: b9a032b6ca185690bd679e1802e6b7af6a2bc43a

run:
  path: sh
  args:
    - -e
    - -c
    - |
      credhub login
      credhub generate --name "$DESTINATION" --type ssh
      credhub get --name "$DESTINATION" --key public_key
