platform: linux

image_resource:
  type: docker-image
  source:
    repository: governmentpaas/bosh-cli-v2
    tag: 864e80c4793e4fca17a2374e8075af119dd03162

run:
  path: sh
  args:
    - -e
    - -c
    - |
      credhub login
      credhub generate --name "$DESTINATION" --type ssh
      credhub get --name "$DESTINATION" --key public_key
