---
platform: linux
inputs:
  - name: paas-cf
  - name: config
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: b9a032b6ca185690bd679e1802e6b7af6a2bc43a
run:
  path: sh
  args:
    - -e
    - -u
    - -c
    - |
      . ./config/config.sh
      if ! curl -I -f "${API_ENDPOINT}/info"; then
        echo "CF API unavailable. Skipping..."
        exit 0
      fi
      if ! echo | cf login -a "${API_ENDPOINT}" -u "${CF_ADMIN}" -p "${CF_PASS}"; then
        echo "Login failed.  Skipping..."
        exit 0
      fi
      if ! cf target -o "${ORG}" -s "${SPACE}"; then
        echo "${ORG}/${SPACE} space doesn't seem to exist. Skipping..."
        exit 0
      fi
      if cf services | grep -q "${DB_NAME}"; then
        # shellcheck disable=SC2153
        for app in ${BOUND_APPS}; do
          cf unbind-service "${app}" "${DB_NAME}" || true
        done
        cf delete-service "${DB_NAME}" -f
      fi
