---
platform: linux
inputs:
  - name: paas-cf
  - name: config
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: e1ffec0d1940706f157a8c1e0ab8131b7084fa1c
run:
  path: sh
  args:
    - -e
    - -u
    - -c
    - |
      . ./config/config.sh
      if ! curl -I -f "${API_ENDPOINT}/info"; then
        echo "CF API unavailable. Skipping..."
        exit 0
      fi

      cf api "${API_ENDPOINT}"

      if ! cf auth "${CF_ADMIN}" "${CF_PASS}"; then
        echo "Login failed.  Skipping..."
        exit 0
      fi

      if ! cf target -o "${ORG}" -s "${SPACE}"; then
        echo "${ORG}/${SPACE} space doesn't seem to exist. Skipping..."
        exit 0
      fi

      if cf services | grep -q "${DB_NAME}"; then
        # shellcheck disable=SC2153
        for app in ${BOUND_APPS}; do
          cf unbind-service "${app}" "${DB_NAME}" || true
        done
        cf delete-service "${DB_NAME}" -f
      fi
