---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-acceptance-tests
    tag: 4467c23cef4a5d87d531b88700300b222fbf2916
inputs:
  - name: paas-cf
  - name: cf-smoke-tests-release
  - name: test-config
outputs:
  - name: artifacts
run:
  path: sh
  args:
  - -c
  - |
    paas-cf/platform-tests/upstream/run_smoke_tests.sh
    TEST_EXIT_CODE=$?
    if [ "$EMAIL_ON_SMOKE_TEST_FAILURE" = "true" ]; then
      if [ "$TEST_EXIT_CODE" -gt 0 ]; then
        paas-cf/concourse/scripts/smoke_tests_email.sh \
          "${DEPLOY_ENV}" "${SYSTEM_DNS_ZONE_NAME}" "${ALERT_EMAIL_ADDRESS}" "${MONITORED_DEPLOY_ENV}"
      fi
    fi
    exit $TEST_EXIT_CODE
