---

- type: replace
  path: /vm_extensions/-
  value:
    name: rds_broker
    cloud_properties:
      iam_instance_profile: rds-broker
      security_groups:
      - ((terraform_outputs_rds_broker_db_clients_security_group))
      - ((terraform_outputs_default_security_group))
      elbs:
      - ((terraform_outputs_rds_broker_elb_name))
      lb_target_groups:
      - ((terraform_outputs_cf_rds_broker_target_group_name))
