---

- type: replace
  path: /vm_extensions/-
  value:
    name: elasticache_broker
    cloud_properties:
      iam_instance_profile: elasticache-broker
      security_groups:
      - ((terraform_outputs_default_security_group))
      elbs:
      - ((terraform_outputs_elasticache_broker_elb_name))
      lb_target_groups:
      - ((terraform_outputs_cf_elasticache_broker_target_group_name))
