- type: replace
  path: /releases/-
  value:
    name: oauth2-proxy
    version: 0.1.1
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/oauth2-proxy-0.1.1.tgz
    sha1: d7cc49ac7aedb263aa7f380949d532d9e4762811

- type: remove
  path: /instance_groups/name=nginx

- type: replace
  path: /instance_groups/-
  value:
    &nginx
    name: nginx_z1
    azs:
      - z1
    instances: 1
    vm_type: nano
    stemcell: default
    networks:
      - name: cf
    vm_extensions:
      - prometheus_lb_z1
    jobs:
      - &nginx_job
        name: nginx
        release: prometheus
        properties:
          nginx:
            alertmanager:
              http_port: 8081
              server_name: prometheus.((domain))
              cross_zone_load_balancing: false
            prometheus:
              http_port: 8081
              cross_zone_load_balancing: false
              server_name: alertmanager.((domain))
            grafana:
              http_port: 3000
              cross_zone_load_balancing: false
      - name: oauth2-proxy
        release: oauth2-proxy
        properties:
          address: http://0.0.0.0:8080
          upstream: http://127.0.0.1:8081
          provider: github
          github-org: "alphagov"
          github-team: "Government PaaS - People"
          email_domain: digital.cabinet-office.gov.uk
          browser_xss_filter: True
          content_type_nosniff: True

- type: replace
  path: /instance_groups/-
  value:
    <<: *nginx
    name: nginx_z2
    azs:
      - z2
    vm_extensions:
      - prometheus_lb_z2
    jobs:
      - <<: *nginx_job
        provides:
          nginx: nil
