- type: replace
  path: /releases/-
  value:
    name: oauth2-proxy
    version: 0.0.1562169186
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/oauth2-proxy-0.0.1562169186.tgz
    sha1: 7b5201ec6b90e13a86b188903b45eff5d001143c


- type: remove
  path: /instance_groups/name=nginx

- type: replace
  path: /instance_groups/-
  value:
    &nginx
    name: nginx_z1
    azs:
      - z1
    instances: 1
    vm_type: nano
    stemcell: default
    networks:
      - name: cf
    vm_extensions:
      - prometheus_lb_z1
    jobs:
      - &nginx_job
        name: nginx
        release: prometheus
        properties:
          nginx:
            server_names_hash_bucket_size: 256
            alertmanager:
              http_port: 9090
              server_name: prometheus-1.((system_domain))
              cross_zone_load_balancing: false
            prometheus:
              http_port: 9090
              cross_zone_load_balancing: false
              server_name: alertmanager-1.((system_domain))
            grafana:
              http_port: 3000
              cross_zone_load_balancing: false
      - name: oauth2-proxy
        release: oauth2-proxy
        properties:
          address: http://0.0.0.0:8080
          upstream: http://127.0.0.1:9090
          provider: github
          github-org: "alphagov"
          github-team: "Government PaaS - People"
          client_id: ((oauth-proxy-client-id))
          client_secret: ((oauth-proxy-client-secret))
          cookie_secret: ((oauth-proxy-cookie-secret))
          email_domain: digital.cabinet-office.gov.uk
          browser_xss_filter: True
          content_type_nosniff: True

- type: replace
  path: /instance_groups/-
  value:
    <<: *nginx
    name: nginx_z2
    azs:
      - z2
    vm_extensions:
      - prometheus_lb_z2
    jobs:
      - <<: *nginx_job
        provides:
          nginx: nil
