- type: remove
  path: /instance_groups/name=nginx

- type: replace
  path: /instance_groups/-
  value:
    &nginx
    name: nginx_z1
    azs:
      - z1
    instances: 1
    vm_type: nano
    stemcell: default
    networks:
      - name: cf
    vm_extensions:
      - prometheus_lb_z1
    jobs:
      - &nginx_job
        name: nginx
        release: prometheus
        properties:
          nginx:
            alertmanager:
              auth_users:
                - name: admin
                  password: ((alertmanager_password))
              cross_zone_load_balancing: false
            prometheus:
              auth_users:
                - name: admin
                  password: ((prometheus_password))
              cross_zone_load_balancing: false
            grafana:
              cross_zone_load_balancing: false
      - name: oauth2-proxy
        release: oauth2-proxy
        properties:
          address: http://0.0.0.0:8080
          upstream: http://127.0.0.1:8081
          provider: oidc
          client_id: ((oauth-proxy-client-id))
          client_secret: ((oauth-proxy-client-secret))
          cookie_secret: ((oauth-proxy-cookie-secret))
          oidc_issuer_url: https://opslogin.fr.cloud.gov/oauth/token
          email_domain: gsa.gov
          browser_xss_filter: True
          content_type_nosniff: True

- type: replace
  path: /instance_groups/-
  value:
    <<: *nginx
    name: nginx_z2
    azs:
      - z2
    vm_extensions:
      - prometheus_lb_z2
    jobs:
      - <<: *nginx_job
        provides:
          nginx: nil
