---
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
    job_name: alertmanager

    file_sd_configs:
      - files:
          - "/var/vcap/store/bosh_exporter/bosh_target_groups.json"

    relabel_configs:
      - source_labels:
          - __meta_bosh_job_process_name
        regex: alertmanager
        action: keep

      - source_labels:
          - __meta_bosh_deployment
        regex: prometheus
        action: keep

      - source_labels:
          - __meta_bosh_deployment
        regex: "(.*)"
        target_label: bosh_deployment

      - source_labels:
          - __address__
        regex: "(.*)"
        target_label: __address__
        replacement: "${1}:9093"
