- type: replace
  path: /instance_groups/name=firehose/networks
  value:
  - name: cf

- type: replace
  path: /instance_groups/name=firehose/vm_type
  value: medium

- type: replace
  path: /instance_groups/name=firehose/jobs/name=firehose_exporter/properties/firehose_exporter/doppler/idle_timeout?
  value: 5m

- type: replace
  path: /instance_groups/-
  value:
    name: firehose
    azs:
      - z1
    instances: 1
    vm_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: firehose_exporter
        release: prometheus
        properties:
          firehose_exporter:
            doppler:
              subscription_id: "((metrics_environment))"
              max_retry_count: 300
              url: wss://doppler.((system_domain)):((traffic_controller_external_port))
            logging:
              url: wss://doppler.((system_domain)):((traffic_controller_external_port))
              use_legacy_firehose: true
            uaa:
              url: https://uaa.((system_domain))
              client_id: firehose_exporter
              client_secret: "((uaa_clients_firehose_exporter_secret))"
            metrics:
              environment: "((metrics_environment))"
            skip_ssl_verify: ((skip_ssl_verify))