---
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
    job_name: paas-auditor
    scrape_interval: 30s
    scheme: https
    static_configs:
      - targets:
          - paas-auditor.((app_domain))
