---
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/scrape_configs/-
  value:
    job_name: bosh-auditor
    scrape_interval: 30s
    scheme: http
    static_configs:
      - targets:
          # This is the BOSH director
          - "10.0.0.6:9275"
